### ISSUE TITLE
Sound effects cut out after a while

### ISSUE THREAD

**Issue by ZT-1** [PARTYMANX/partymod-thps3#13]
The only way I can see as to replicating this is to start a level in career, then end run and retry a few times. Eventually, skater, ui, and ambient sounds will gradually start to cut out until they completely stop playing. Backing out to the menu then restarting the level is a workaround but not a permeant fix.

https://streamable.com/otxwdt

**Comment by Reonu** [comment]
Can confirm

**Comment by ks202005** [comment]
This bug seems to have existed [since the original PC launch](https://www.neoseeker.com/forums/1577/t87458-problem-with-sound/), so I don't think it's an issue with PARTYMOD. I have this issue as well. 

Edit: I actually can't confirm whether or not the Neoseeker forum post deals with the PC version or not. The thread seems to belong to the Xbox forums but I honestly can't tell for sure.

**Comment by ZT-1** [comment]
Yes, it is a vanilla game bug. I was documenting normal game bugs as well here.

**Comment by PARTYMANX** [comment]
I keep meaning to chime in if only for my own notes, I did briefly look into this while working on the IL mode.  I think it's something wrong with the cleanup code run after retry.  I also noticed that when `printf` is hooked, you can see console output stating that sound playback failed, so I'm lead to believe it's not and issue with the sound engine, which was my biggest fear.  But who knows, maybe memory mismanagement is even worse...

**Comment by not6** [comment]
I found the issue and a potential fix, for some reason the audio cleanup function is called when you quit to the main menu but not when you retry a level, which means it doesn't actually stop the sounds that are playing before you retry the level. Retrying enough times causes the game to have no room for more sounds, so they fail to play. The function that the main menu cleanup code calls to stop all sounds is at VA 0x4C4330, I think if you call this in the level retry cleanup code the issue will be fixed. I hope this helps @PARTYMANX 

EDIT: If you place a call to 408C30 right after the cleanup call at 439B1C, the issue seems to be fixed! Calling the other function I mentioned instead breaks sound

**Comment by PARTYMANX** [comment]
I just implemented it and played Canada as an IL for a while and yep, it seems like it works.  Excellent find!  Should be out soon, there's something else I want to chase down tonight.

**Comment by PARTYMANX** [comment]
1.1.3 includes the fix
